### ISSUE TITLE
Sketch can't write to Seeeduino XIAO using board package 1.7.3

### ISSUE THREAD

**Issue by matsujirushi** [Seeed-Studio/ArduinoCore-samd#10]
```
{runtime.tools.bossac-1.7.0-arduino3.path}/bossac.exe -i -d --port=COM33 -U true -i -e -w -v C:\Users\takashi\AppData\Local\Temp\arduino_build_148209/sketch_may10a.ino.bin -R 
java.io.IOException: Cannot run program "{runtime.tools.bossac-1.7.0-arduino3.path}/bossac.exe": CreateProcess error=2, 指定されたファイルが見つかりません。
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at processing.app.helpers.ProcessUtils.exec(ProcessUtils.java:26)
	at cc.arduino.packages.Uploader.executeUploadCommand(Uploader.java:129)
	at cc.arduino.packages.uploaders.SerialUploader.runCommand(SerialUploader.java:383)
	at cc.arduino.packages.uploaders.SerialUploader.uploadUsingPreferences(SerialUploader.java:197)
	at cc.arduino.UploaderUtils.upload(UploaderUtils.java:77)
	at processing.app.SketchController.upload(SketchController.java:732)
	at processing.app.SketchController.exportApplet(SketchController.java:703)
	at processing.app.Editor$UploadHandler.run(Editor.java:2047)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: CreateProcess error=2, 指定されたファイルが見つかりません。
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 9 more
スケッチの書き込み中にエラーが発生しました
```

**Comment by matsujirushi** [comment]
FYI
https://twitter.com/qx5k_iskw/status/1259416713637924865
https://twitter.com/toukatu_giken/status/1259441795001278464

**Comment by matsujirushi** [comment]
**Solution:**
![image](https://user-images.githubusercontent.com/8079404/81498667-37e18b80-9301-11ea-9ae3-8268f6631f11.png)
